var tabledata = [{
    id: 1,
    usecasetype: "Code and IT development",
    worktitle: "SAS to R translation",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf",
    resourcetype: "Paper",
    organisation: "CSO Ireland",
    date: "2023-12",
    aimodels: "GPT-3.5",
    approach: " ",
    tools: " ",
    codeavailability: ""
},
{
    id: 2,
    usecasetype: "Code and IT development",
    worktitle: "SAS to R conversion: the use of LLM",
    link: "https://my.visme.co/view/z4nodvzv-gpt-for-sas-to-r-slides-for-geneva#s1",
    resourcetype: "Presentation",
    organisation: "France Insee",
    date: "2023-11",
    aimodels: "GPT-3.5",
    approach: " ",
    tools: " ",
    codeavailability: ""
},
{
    id: 3,
    usecasetype: "Text generation for analysis",
    worktitle: "Report Generation Using LLMs",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf",
    resourcetype: "Paper",
    organisation: "Statistics Canada",
    date: "2023-11",
    aimodels: "GPT-3.5",
    approach: " ",
    tools: " ",
    codeavailability: ""
},
{
    id: 4,
    usecasetype: "Text generation for analysis",
    worktitle: "AI in Statistics Norway",
    link: "", // https://statswiki.unece.org/download/attachments/449708474/AI%20in%20Statistics%20Norway_.pdf?version=1&modificationDate=1718780512694&api=v2
    resourcetype: "Presentation",
    organisation: "Statistics Norway",
    date: "2024-05",
    aimodels: "GPT-4",
    approach: "Prompt engineering",
    tools: "Chat GPT",
    codeavailability: "N/A"
},
{
    id: 5,
    usecasetype: "Text generation for data processing (editing)",
    worktitle: "Leveraging AI-assistants for better metadata and communication",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf",
    resourcetype: "Presentation",
    organisation: "Bank of International Settlements",
    date: "2024-03",
    aimodels: "GPT-3.5",
    approach: "Prompt engineering, RAG",
    tools: "OpenAI AI Assistant",
    codeavailability: "N/A"
},
{
    id: 6,
    usecasetype: "Communication - textual materials",
    worktitle: "Use of AI in the communication and dissemination of statistics",
    link: "", // https://statswiki.unece.org/download/attachments/449708474/2024-04%20BIS%20Metadata%20editing%20leveraging%20GPT.pdf?version=1&modificationDate=1714557129914&api=v2
    resourcetype: "Presentation",
    organisation: "Indonesia BIS",
    date: "2024-03",
    aimodels: "GPT-3.5",
    approach: "Prompt engineering",
    tools: " ",
    codeavailability: "N/A"
},
{
    id: 7,
    usecasetype: "Communication - images or videos materials",
    worktitle: "Use of Generative AI in ESTAT",
    link: "", // https://statswiki.unece.org/download/attachments/449708474/2024-04%20BIS%20Metadata%20editing%20leveraging%20GPT.pdf?version=1&modificationDate=1714557129914&api=v2
    resourcetype: "Presentation",
    organisation: "EUROSTAT",
    date: "2024-04",
    aimodels: " ",
    approach: "Prompt engineering",
    tools: "DALL.E, ChatGPT, Adobe Firefly, Image Creator, Midjourney",
    codeavailability: "N/A"
},
{
    id: 8,
    usecasetype: "Data dissemination and information search",
    worktitle: "Free to play: UNCTAD's experience with developing its own open-source RAG LLM application",
    link: "https://unece.org/sites/default/files/2024-05/ECE_CES_2024_23_E.pdf",
    resourcetype: "Paper",
    organisation: "UNCTAD",
    date: "2024-05",
    aimodels: "mistral",
    approach: "RAG",
    tools: "LlamaIndex, PostgreSQL, Streamlit",
    codeavailability: "Yes"
},
{
    id: 9,
    usecasetype: "Data dissemination and information search",
    worktitle: "Free to play: UNCTAD's experience with developing its own open-source RAG LLM application",
    link: "https://unece.org/sites/default/files/2024-06/5_2_4_AI%20and%20LLM_UNCTAD_DanielHopp.pdf",
    resourcetype: "Presentation",
    organisation: "UNCTAD",
    date: "2024-04",
    aimodels: "mistral",
    approach: "RAG",
    tools: "LlamaIndex, PostgreSQL, Streamlit",
    codeavailability: "Yes"
},
{
    id: 10,
    usecasetype: "Data dissemination and information search",
    worktitle: "Using large language models (LLMs) to improve website search experience with StatsChat ",
    link: "https://datasciencecampus.ons.gov.uk/using-large-language-models-llms-to-improve-website-search-experience-with-statschat/",
    resourcetype: "Blog",
    organisation: "UK ONS",
    date: "2023-08",
    aimodels: "Flan-T5; all-mpnet-base-v2",
    approach: "RAG",
    tools: " ",
    codeavailability: "Yes"
},
{
    id: 11,
    usecasetype: "Data dissemination and information search",
    worktitle: "Statbot.Swiss A Chatbot to query Swiss Open Data",
    link: "https://unece.org/sites/default/files/2024-06/5_2_2_AI%20and%20LLM_Switzerland_BertrandLoison.pdf",
    resourcetype: "Presentation",
    organisation: "Switzerland FSO",
    date: "2024-06",
    aimodels: " ",
    approach: " ",
    tools: " ",
    codeavailability: "Yes"
},
{
    id: 12,
    usecasetype: "Data dissemination and information search, Communication - images or videos materials",
    worktitle: "Text based intelligent assistant: TIA",
    link: "", // https://statswiki.unece.org/download/attachments/449708474/TIA%20platform_Deutsche%20Bundesbank_D%C3%BCker.pptx?version=1&modificationDate=1718699097322&api=v2
    resourcetype: "Presentation",
    organisation: "Bundesbank Germany",
    date: "2024-06",
    aimodels: "GPT-3.5, GPT-4 Turbo, GPT-4",
    approach: "Prompt engineering ",
    tools: "Chat GPT via Azure Microsoft Cloud Service",
    codeavailability: " "
},
{
    id: 13,
    usecasetype: "Data dissemination and information search",
    worktitle: "Stat GPT - Exploring Official Statistics using Generative AI and SDMX",
    link: "https://unece.org/sites/default/files/2024-06/5_2_3_AI%20and%20LLM_IMF_BertKroese.pdf",
    resourcetype: "Presentation",
    organisation: "IMF",
    date: "2024-06",
    aimodels: "",
    approach: "Multi agent",
    tools: "",
    codeavailability: " "
},
{
    id: 14,
    usecasetype: "Data dissemination and information search",
    worktitle: "Stat GPT - Exploring Official Statistics using Generative AI and SDMX",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf",
    resourcetype: "Paper",
    organisation: "IMF",
    date: "2023-11",
    aimodels: "GPT-3.5, GPT-4",
    approach: "",
    tools: "AI-Dial",
    codeavailability: " "
},
{
    id: 15,
    usecasetype: "Text generation for data processing",
    worktitle: "Updating Statistical Classification Definitions",
    link: "https://unece.org/sites/default/files/2023-12/HLGMOS%20LLM%20Paper_Preprint_1.pdf",
    resourcetype: "Paper",
    organisation: "Australian Bureau of Statistics",
    date: "2023-11",
    aimodels: "",
    approach: "",
    tools: "",
    codeavailability: " "
},
{
    id: 16,
    usecasetype: "Data dissemination and information search",
    worktitle: "Adopting artificial intelligence in the production and dissemination of official statistics",
    link: "https://unece.org/sites/default/files/2024-05/ECE_CES_2024_21_E.pdf",
    resourcetype: "Paper",
    organisation: "Statistics Norway",
    date: "2024-05",
    aimodels: "",
    approach: "RAG",
    tools: "LangChain, Chainlit, PandasAI",
    codeavailability: " "
},
{
    id: 17,
    usecasetype: "Text generation for data processing",
    worktitle: "Adopting artificial intelligence in the production and dissemination of official statistics",
    link: "https://datasciencecampus.ons.gov.uk/classifai-exploring-the-use-of-large-language-models-llms-to-assign-free-text-to-commonly-used-classifications/",
    resourcetype: "Blog",
    organisation: "UK ONS",
    date: "2024-07",
    aimodels: " MiniLM, Gemini-Pro",
    approach: "RAG",
    tools: "LangChain, Streamlit",
    codeavailability: "Yes"
},
{
    id: 18,
    usecasetype: "Data dissemination and information search",
    worktitle: "SDMX + AI: A path to explore generative AI for better data accessibility",
    link: "https://siscc.org/sdmxai/",
    resourcetype: "Workshop",
    organisation: "OECD & BIS",
    date: "2024-04",
    aimodels: "GPT-3.5, GPT-4",
    approach: "RAG",
    tools: "Stat GPT (IMF), .Stat LLM-based Search POC (SEASE), StatsBot POC (e-Zest), ChatHMS (HMS)",
    codeavailability: "N/A"
} 
]
